
skillMetadata:
  sections:
    - name: Keyboard Shortcut
      fields:
        - type: label
          label: The keyboard shortcut can be one or more keys separated by a + sign. It's recommended to use a multi-key shortcut to prevent the listener triggering while typing normally.
        - name: key_combo
          type: text
          label: Keyboard Shortcut to use
          value: <ctrl>+<alt>+r
          placeholder: <ctrl>+<alt>+r